
# Description: Docker compose to bring up environment for API
# Author: neatMon, Inc.
# License: MIT

version: "3.8"
services:
    neatmon-api:
        env_file:
            - ./config/.env
        container_name: api
        hostname: api-server
        volumes:
            - "./server:/usr/src/app"
            - "/opt/howeneat/AMN-Firmware:/usr/src/apiFiles"
        build: ./server
        ports:
            - "1330:5000"
        restart: always
        command: "node /usr/src/app/index.js"
        depends_on:
            - "redis"
    worker:
        build: ./server
        env_file:
            - ./config/.env
        volumes:
            - "./server:/usr/src/app"
        depends_on:
            - redis
        restart: always
        command: node /usr/src/app/worker.js
    redis:
        image: redis:alpine
        expose:
            - "6379"
        restart: always
