
# Description: Docker compose to bring up environment for API
# Author: neatMon, Inc.
# License: MIT

version: "3.8"
services:
    mongoDB:
        # https://hub.docker.com/_/mongo
        container_name: mongoDB
        hostname: mongo-database
        image: mongo
        volumes:
            - ./database/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
            - ./database:/tmp/data
        ports:
            - "27017:27017"
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
            - MONGO_INITDB_DATABASE=${MONGO_DATABASE_NAME}
        command: mongod
        restart: always
    neatmon-api:
        env_file:
            - ./config/.env
        container_name: api
        hostname: api-server
        volumes:
            - "./server:/usr/src/app"
            - "/opt/howeneat/AMN-Firmware:/usr/src/apiFiles"
        build: ./server
        ports:
            - "1330:5000"
        restart: always
        command: "node /usr/src/app/index.js"
        depends_on:
            - "mongoDB"
            - "redis"
    worker:
        build: ./server
        env_file:
            - ./config/.env
        volumes:
            - "./server:/usr/src/app"
        depends_on:
            - redis
        restart: always
        command: node /usr/src/app/worker.js
    redis:
        image: redis:alpine
        expose:
            - "6379"