openapi: 3.0.3

info:
  title: neatMon Open Source API
  description: |-
    This is documentation for the neatMon Open Source API, to find out more about neatMon products please visit [Our Homepage](https://www.neatmon.com). 
    
    Some useful links:
    - [Knowledge Base](https://info.neatmon.com)
  termsOfService: https://hub.neatmon.com/terms
  contact:
    email: info@neatmon.com
  license:
    name: MIT License
    url: https://github.com/neatMon-Inc/neatmon.api/blob/workerQueue/LICENSE
  version: 1.0.11

externalDocs:
  description: neatMon open source API software repo
  url: https://github.com/neatMon-Inc/neatmon.api

servers:
  - url: https://api.neatmon.io:1330
    description: neatMon API production server

paths:
  /api/device/data/{m_guid}:
    get:
      description: 'Returns all data for a given GUID starting with the latest. Note:
        This endpoint has a rate limit of 500 requests per 15 minutes.'
      parameters:
      - description: GUID of the device
        in: path
        name: m_guid
        required: true
        schema:
          type: string
      - description: Start time in Unix timestamp
        in: query
        name: start
        schema:
          type: integer
      - description: End time in Unix timestamp
        in: query
        name: end
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  type: object
                type: array
          description: Data for the given GUID
        '400':
          description: Query results exceed limits
        '500':
          description: Internal server error
      summary: Get the status of a GUID
  /api/device/{p_guid}:
    post:
      description: 'Receives data from devices, processes it, and returns relevant
        control commands if any exist. This endpoint spawns a worker to handle background
        tasks related to data storage, processing, and forwarding. Note: This endpoint
        has a rate limit of 500 requests per 15 minutes.'
      parameters:
      - description: GUID of the device
        in: path
        name: p_guid
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeviceData'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  cmd:
                    description: Commands to be sent to the device, if any, from controlQueue
                      and commandQueue.
                    properties:
                      cfg:
                        description: Configuration update command, if available.
                        type: object
                      control:
                        description: List of control commands to be executed on the
                          device.
                        items:
                          type: string
                        type: array
                      fwu:
                        description: Firmware update command, if available.
                        properties:
                          crc:
                            description: CRC-32 checksum for the firmware update file.
                            type: string
                          uri:
                            description: URI for the firmware update file.
                            type: string
                        type: object
                    type: object
                  t:
                    description: Current server timestamp in seconds.
                    type: integer
                type: object
          description: Data processed successfully
        '400':
          description: Bad request (e.g., invalid JSON or incorrect CRC)
        '500':
          description: Internal server error
      summary: Handle device data post
  /api/status:
    get:
      description: 'Useful for uptime monitoring of the API by a third party. Note:
        This endpoint has a rate limit of 500 requests per 15 minutes.'
      responses:
        '200':
          content:
            text/plain:
              schema:
                example: API Working Mon Aug 29 2024 10:00:00 GMT+0000 (Coordinated
                  Universal Time)
                type: string
          description: API is working
      summary: Get the status of the API
  /api/status/time:
    get:
      description: 'Returns the current server time as a timestamp. Note: This endpoint
        has a rate limit of 500 requests per 15 minutes.'
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  t:
                    example: 1622547802
                    type: integer
                type: object
          description: Current timestamp
      summary: Get the current time in timestamp format
  /files/{filename}:
    get:
      description: 'Retrieves a file from the server, typically for firmware updates.
        Note: This endpoint has a rate limit of 500 requests per 15 minutes.'
      parameters:
      - description: Name of the file
        in: path
        name: filename
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/octet-stream:
              schema:
                format: binary
                type: string
          description: File retrieved successfully
          headers:
            CRC-32:
              description: CRC-32 checksum of the response body for data integrity.
              schema:
                type: string
            Content-Length:
              description: The length of the response body.
              schema:
                type: integer
            Content-Range:
              description: The range of bytes being served.
              schema:
                type: string
            Content-Type:
              description: The content type of the response, always `application/octet-stream`.
              schema:
                example: application/octet-stream
                type: string
        '400':
          description: Bad request, e.g., missing range header or invalid range.
        '403':
          description: Forbidden - the requested file path is outside the allowed
            directory.
        '404':
          description: File not found.
        '416':
          description: Requested range not satisfiable, e.g., start byte is greater
            than file size.
        '500':
          description: Internal server error, e.g., error while downloading file or
            calculating CRC32.
      summary: Get a file from the API server

components:
  schemas:
    CommandResponse:
      properties:
        cmd:
          description: Commands to be sent to the device, if any, from controlQueue
            and commandQueue.
          properties:
            cfg:
              description: Configuration update command, if available.
              type: object
            control:
              description: List of control commands to be executed on the device.
              items:
                type: string
              type: array
            fwu:
              description: Firmware update command, if available.
              properties:
                crc:
                  description: CRC-32 checksum for the firmware update file.
                  type: string
                uri:
                  description: URI for the firmware update file.
                  type: string
              type: object
          type: object
        t:
          description: Current server timestamp in seconds.
          type: integer
      type: object
    DeviceData:
      properties:
        fw:
          type: string
        hw:
          type: string
        id:
          type: string
        pn:
          type: string
        v:
          additionalProperties:
            properties:
              data:
                type: number
              ts:
                type: integer
            type: object
          type: object
      type: object